# GitHub Actions workflow to build LaTeX PDF using dante-ev/latex-action
# Maintained by Deutschsprachige Anwendervereinigung TeX e.V.
# https://github.com/dante-ev/latex-action

name: Build LaTeX Document

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 0 2 * *'  # Run monthly on the 2nd at 00:00

jobs:
  build_latex:
    name: Compile LaTeX PDF
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug - List files
        run: |
          echo "Current directory:"
          pwd
          echo "Files in directory:"
          ls -la
          echo "Bibliography file:"
          ls -la Bibliography.bib || echo "Bibliography.bib not found"
          echo "First 10 lines of Bibliography.bib:"
          head -n 10 Bibliography.bib || echo "Cannot read Bibliography.bib"

      - name: Compile LaTeX document (First Pass)
        uses: dante-ev/latex-action@latest
        with:
          root_file: thesis.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -file-line-error

      - name: Run Biber
        uses: dante-ev/latex-action@latest
        with:
          root_file: thesis
          compiler: biber

      - name: Compile LaTeX document (Second Pass)
        uses: dante-ev/latex-action@latest
        with:
          root_file: thesis.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -file-line-error

      - name: Compile LaTeX document (Third Pass)
        uses: dante-ev/latex-action@latest
        with:
          root_file: thesis.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -file-line-error

      - name: Rename compiled PDF
        run: mv thesis.pdf thesis_mendez_gomez_jose_2025.pdf

      - name: Upload Compiled PDF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: thesis-pdf
          path: thesis_mendez_gomez_jose_2025.pdf
          