# GitHub Actions workflow to build LaTeX PDF using dante-ev/latex-action
# Maintained by Deutschsprachige Anwendervereinigung TeX e.V.
# https://github.com/dante-ev/latex-action

name: Build LaTeX Document

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 0 2 * *'  # Run monthly on the 2nd at 00:00

jobs:
  build_latex:
    name: Compile LaTeX PDF
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document with latexmk
        uses: dante-ev/latex-action@latest
        with:
          root_file: thesis.tex
          compiler: latexmk
          args: -pdf -r .latexmkrc -g -f
        continue-on-error: true  # Continue even if latexmk returns non-zero exit code

      - name: Check PDF creation
        run: |
          if [ -f thesis.pdf ]; then
            echo "✅ PDF created successfully!"
            ls -lh thesis.pdf
          else
            echo "❌ PDF not found"
            exit 1
          fi

      - name: Rename compiled PDF
        run: mv thesis.pdf thesis_mendez_gomez_jose_2025.pdf

      - name: Upload Compiled PDF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: thesis-pdf
          path: thesis_mendez_gomez_jose_2025.pdf
